[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --prod=false && pnpm run build"

[deploy]
startCommand = "pnpm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300
numReplicas = 1
